### ISSUE TITLE
inputs and buttons don't have explicit color

### ISSUE THREAD

**Issue by pooley182** [geuis/helium-css#27]
The text area and buttons have a default background-color of #fff.
However, they're inheriting styles for color from other css within the page. If this also happens to be white then my text can't be seen.

**Comment by geuis** [comment]
Can you drop a link to the site where its happening? The css might need to be more specific

**Comment by pooley182** [comment]
I can't give you a link because it was on a local dev environment.
However, It's not a specificity issue. On line 362 you define the css for "#cssdetectID input" you give it an explicit background of #fff but don't specify a color.
If my css for input was background: #666; color #fff; then I'm going to end up with white text on a white background.

**Comment by geuis** [comment]
Thanks for catching that. This should fix it I think. https://github.com/geuis/helium-css/commit/049594bc6e84c50574b2f55e6e7730104ea96efa
