### ISSUE TITLE
Seems to loop through pages endlessly?

### ISSUE THREAD

**Issue by Nantris** [geuis/helium-css#30]
How many loops of the page list should this script go through? I am wondering if it is working properly. I've been through every page at least 3 times now.

Thanks for the great work. If you could let me know if this is normal operation, I would appreciate it a lot!

**Comment by geuis** [comment]
@Slapbox It should only loop through 2x. First pass is to gather all of the linked stylesheets and load their content via xhr requests. Second pass is where the found selectors are tested against the urls you provide.

**Comment by Nantris** [comment]
Thank you very much. It did eventually finish for me.

**Comment by geuis** [comment]
@Slapbox After it finished running, are the results as expected? I haven't updated Helium in a while.

**Comment by Nantris** [comment]
I don't recall if the rules it flagged were appropriate or not, but for several reasons I ended up not being able to use the results. This is mainly because media queries make life hell for everyone. It's a cool tool though and definitely has some use cases.

**Comment by geuis** [comment]
ooh right. Media queries weren't a thing when Helium was initially created. Thanks for pointing that out. Filing an issue on it.
